### ISSUE TITLE
Fatal error: Class 'Memcached' not found

### ISSUE THREAD

**Issue by swatinsk** [0plus1/lumendingojwtapi#2]
Hi,

I have downloaded project, ran the '$ composer update' command, updated .env file
And got following error. Please help ASAP
Fatal error: Class 'Memcached' not found in /Users/Development/webroot/lumendingojwtapi/vendor/illuminate/cache/MemcachedConnector.php on line 51

Thanks,
Swati.

**Comment by 0plus1** [comment]
You need to install memcached on your webserver: http://php.net/manual/en/memcached.setup.php

**Comment by KyleMassacre** [comment]
Or in your .env file change

```
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=database
```

to

```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
```
