### ISSUE TITLE
  Argument 3 passed to Tymon\JWTAuth\Providers\JWT\Namshi::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by mohuishou** [0plus1/lumendingojwtapi#3]
When I run  php artisan jwt:secret ，this  error occurred
`Argument 3 passed to Tymon\JWTAuth\Providers\JWT\Namshi::__construct() must be of the type array, null given`

**Comment by 0plus1** [comment]
I think this has to do with the newest version if you run composer update
Latest tested hash is: dev-develop 2c28de3

**Comment by 0plus1** [comment]
This has to do with Lumen 5.2 I am testing this and at the moment neither libraries play nice with it.

**Comment by mohuishou** [comment]
Yes，this has too much error，so now I use Lumen 5.1. THX
