### ISSUE TITLE
homestead Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException

### ISSUE THREAD

**Issue by ghost** [0plus1/lumendingojwtapi#5]
homestead develop env test with POSTMAN url:http://h.lumendingojwtapi:8000/v1/authenticate 
return the below errors:

> {
>   "message": "404 Not Found",
>   "status_code": 404,
>   "debug": {
>     "line": 1256,
>     "file": "/home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php",
>     "class": "Symfony\Component\HttpKernel\Exception\NotFoundHttpException",
>     "trace": [
>       "#0 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1212): Laravel\Lumen\Application->handleDispatcherResponse(Array)",
>       "#1 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1442): Laravel\Lumen\Application->Laravel\Lumen\{closure}()",
>       "#2 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1213): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))",
>       "#3 /home/vagrant/Code/lumendingojwtapi/vendor/dingo/api/src/Routing/Adapter/Lumen.php(103): Laravel\Lumen\Application->dispatch(Object(Dingo\Api\Http\Request))",
>       "#4 /home/vagrant/Code/lumendingojwtapi/vendor/dingo/api/src/Routing/Router.php(575): Dingo\Api\Routing\Adapter\Lumen->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
>       "#5 /home/vagrant/Code/lumendingojwtapi/vendor/dingo/api/src/Http/Middleware/Request.php(123): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
>       "#6 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
>       "#7 /home/vagrant/Code/lumendingojwtapi/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
>       "#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
>       "#9 /home/vagrant/Code/lumendingojwtapi/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
>       "#10 /home/vagrant/Code/lumendingojwtapi/vendor/dingo/api/src/Http/Middleware/Request.php(124): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
>       "#11 /home/vagrant/Code/lumendingojwtapi/vendor/dingo/api/src/Http/Middleware/Request.php(100): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
>       "#12 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))",
>       "#13 /home/vagrant/Code/lumendingojwtapi/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
>       "#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
>       "#15 /home/vagrant/Code/lumendingojwtapi/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
>       "#16 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1439): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
>       "#17 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1213): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))",
>       "#18 /home/vagrant/Code/lumendingojwtapi/vendor/laravel/lumen-framework/src/Application.php(1153): Laravel\Lumen\Application->dispatch(NULL)",
>       "#19 /home/vagrant/Code/lumendingojwtapi/public/index.php(28): Laravel\Lumen\Application->run()",
>       "#20 {main}"
>     ]
>   }
> }`

**Comment by ramyareye** [comment]
I had the same problem ! remove v1 !
